spring.application.name=bodybuilder
server.port=8080

spring.mongodb.uri=${MONGODB_URI}
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

# Tag global — aparece em todas as métricas no Grafana
management.metrics.tags.application=register-athlete